[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webm"
  [headers.values]
    Content-Type = "video/webm"
    Accept-Ranges = "bytes"
    Cache-Control = "public, max-age=31536000, immutable"
